{
 "title": "Sidekiq Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Enqueuing rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_enqueued_jobs[1m]))"
    }
   ]
  },
  {
   "title": "Processing rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_processed_jobs_total[1m]))"
    }
   ]
  },
  {
   "title": "Failed growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(sidekiq_failed_jobs_total[1m]))"
    }
   ]
  },
  {
   "title": "Retry jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(sidekiq_retry_jobs)" }
   ]
  },
  {
   "title": "Dead jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(sidekiq_dead_jobs)" }
   ]
  },
  {
   "title": "Enqueued jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(sidekiq_enqueued_jobs)" }
   ]
  },
  {
   "title": "Busy workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(sidekiq_busy_workers)" }
   ]
  },
  {
   "title": "Scheduled jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(sidekiq_scheduled_jobs)" }
   ]
  },
  {
   "title": "Queues latency",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(sidekiq_queue_latency_seconds[1m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(sidekiq_processed_jobs_total[1m])",
     "legendFormat": "processing rate"
    }
   ]
  },
  {
   "title": "Queue enqueued jobs",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_queue_enqueued_jobs)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}